### ISSUE TITLE
CSS Framework Bulma 笔记

### ISSUE THREAD

**Issue by dolphin836** [dolphin836/dolphin836.github.io#18]
#### 圆形按钮

```css
.button.is-circle {
    border-radius: 9999px;
}
```
